# Dockerfile.server

# 1. 使用輕量級的Python官方映像檔
FROM python:3.9-slim

# 2. 設定工作目錄
WORKDIR /app

# 3. 將伺服器程式複製進容器
COPY udp_server.py .

# 4. 當容器啟動時，執行的指令
# -u 參數是為了讓 print 的輸出不要被緩衝，能即時顯示
CMD ["python", "-u", "udp_server.py"]